require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 50

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
